services:
  qacc-be:
    container_name: qacc-be
    #build: .
    image: ghcr.io/generalmagicio/qacc-be:staging
    command: npm run start:docker:server
    environment:
      - ENVIRONMENT=production
      - LOG_PATH=/usr/src/app/logs/qacc.log
    restart: always
    volumes:
      - ./config:/usr/src/app/config
      - ./config:/usr/src/app/build/config
      - ./logs:/usr/src/app/logs
    networks:
      - qacc
    ports:
      - "4001:4000"

  qacc-redis:
    container_name: qacc-redis
    image: redis:7-alpine
    environment:
      - REDIS_ALLOW_EMPTY_PASSWORD=yes
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - qacc
    ports:
      - "6379:6379"

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    networks:
      - qacc
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    environment:
      - MY_URL=${MY_URL:-}
      #- IP_WHITELIST=${IP_WHITELIST:-}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile

volumes:
  redis-data:
  caddy_config:
  caddy_data:

networks:
  qacc: