version: '3.3'

# This docker-compose is just for testing dockerfile locally but if you want to work on something
# I suggest you just use "npm start" and run application outside of docker, beucase this will not support watching changes
services:
  impact-graph:
    build:
      context: .
    command: npm run start:docker:locally
    environment:
      - ENVIRONMENT=local
      - LOG_PATH=/usr/src/app/logs/impact-graph.log
    restart: always
    volumes:
      # You should have a production.env file in the config folder
      # We should bind config in two path, I think because running migrations(ts) needs one and running
      # application(js) read from another path, if we change migrations two run them as js files then we need just on binding
      - type: bind
        source: ./config
        target: /usr/src/app/config
      - type: bind
        source: ./config
        target: /usr/src/app/build/config
      - type: bind
        source: ./logs
        target: /usr/src/app/logs
    ports:
      - "4001:4000"

networks:
  giveth:
    external: true
