services:
  qacc-be:
    container_name: qacc-be
    build: .
    command: npm run start:docker:locally
    environment:
      - ENVIRONMENT=local
      - LOG_PATH=/usr/src/app/logs/qacc.log
    restart: always
    volumes:
      - ./config:/usr/src/app/config
      - ./config:/usr/src/app/build/config
      - ./logs:/usr/src/app/logs
    ports:
      - "4001:4000"

  qacc-postgres:
    container_name: qacc-postgres
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_DB=qacc
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  qacc-redis:
    container_name: qacc-redis
    image: redis:7-alpine
    environment:
      - REDIS_ALLOW_EMPTY_PASSWORD=yes
    restart: always
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  db-data:
  redis-data: