services:
  qacc-be:
    container_name: qacc-be
    image: ghcr.io/generalmagicio/qacc-be:main
    command: npm run start:docker:server
    environment:
      - ENVIRONMENT=production
      - LOG_PATH=/usr/src/app/logs/qacc.log
    restart: always
    volumes:
      - ./config:/usr/src/app/config
      - ./config:/usr/src/app/build/config
      - ./logs:/usr/src/app/logs
    ports:
      - "4001:4000"

  qacc-redis:
    container_name: qacc-redis
    image: redis:7-alpine
    environment:
      - REDIS_ALLOW_EMPTY_PASSWORD=yes
    restart: always
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  redis-data:
