name: Run Inverter Sync Script

on:
  schedule:
    - cron: '0 0 * * 1,6' # Runs at midnight every Monday and Saturday
  workflow_dispatch: # This allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into Server and Install Node.js
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USERNAME }}
          key: ${{ secrets.STAGING_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            curl -sL https://deb.nodesource.com/setup_20.x | sudo -E bash -
            sudo apt-get install -y nodejs

      - name: Pull Latest Code
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USERNAME }}
          key: ${{ secrets.STAGING_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd QAcc-BE
            git pull

      - name: Install Dependencies
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USERNAME }}
          key: ${{ secrets.STAGING_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd QAcc-BE
            npm install

      - name: Build the Project
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USERNAME }}
          key: ${{ secrets.STAGING_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd QAcc-BE
            npm run build

      - name: Run Inverter Sync Script
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USERNAME }}
          key: ${{ secrets.STAGING_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd QAcc-BE
            npm run sync:inverter:production
