name: Run Inverter Sync Script

on:
  schedule:
    - cron: '0 0 * * 1,6' # Runs at midnight every Monday and Saturday
  workflow_dispatch: # This allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into Server and Run Inverter Sync Script
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USERNAME }}
          key: ${{ secrets.STAGING_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            curl -sL https://deb.nodesource.com/setup_20.x | sudo -E bash -
            sudo apt-get install -y nodejs
            cd QAcc-BE
            git pull
            npm install
            npm run build
            npm run sync:inverter:production
